[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "netrunner"
version = "0.1a"
dependencies = [ "requests", "scikit-learn" ]

[project.scripts]
netrunner-cluster = "netrunner.cluster.__main__:main"